module.exports.descriptors = [
  "Forest",
  "Ancient",
  "Petrified",
  "Roaring",
  "Cascade",
  "Tumbling",
  "Silent",
  "Redwood",
  "Bullfrog",
  "Maple",
  "Misty",
  "Elk",
  "Grizzly",
  "Ocean",
  "Sea",
  "Sky",
  "Dusty",
  "Diamond",
];

module.exports.places = [
  "Flats",
  "Village",
  "Canyon",
  "Pond",
  "Group Camp",
  "Horse Camp",
  "Ghost Town",
  "Camp",
  "Dispersed Camp",
  "Backcountry",
  "River",
  "Creek",
  "Creekside",
  "Bay",
  "Spring",
  "Bayshore",
  "Sands",
  "Mule Camp",
  "Hunting Camp",
  "Cliffs",
  "Hollow",
];


module.exports.campDescription = [
  "TRADITIONAL CAMP",
  "RELIGIOUS CAMP",
  "YMCA CAMP",
  "GIRL GUIDE CAMP",
  "WILDERNESS CAMP",
  "CAMP FOR UNDERPRIVILEGED CHILDREN",
  "CAMP FOR PEOPLE WITH LEARNING DISABILITIES AND/OR DEVELOPMENTAL DELAYS",
  "CAMP FOR PEOPLE WITH PHYSICAL DISABILITIES",
];